---

- hosts: windows
  connection: winrm
  gather_facts: False

  tasks:
  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
      path: C:\Users\Administrator\Downloads\foo.conf
      state: touch
