---

- hosts: windows
  connection: winrm
  gather_facts: False

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Output first disk size
    debug:
      var: ansible_facts

  - debug: var=ansible_facts.disks[0].serial_number
    
