---
- hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Query all contract subject
    aci_contract_subject:
      host: "{{ aci_ip }}"
      username: "{{ aci_username }}"
      password: "{{ aci_userpass }}"
      validate_certs: no
      state: query
    register: current

  - debug:
      var: current
