---
- hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Query all AEP to domain bindings
    aci_aep_to_domain: &binding_query
      host: "{{ aci_ip }}"
      username: "{{ aci_username }}"
      password: "{{ aci_userpass }}"
      validate_certs: no
      state: query
    register: current

  - debug:
      var: current
