---

- hosts: AWX
  connection: ssh
  gather_facts: False
  become: true

  tasks:
  - name: add epel repo
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no
      enabled: yes

  - name: install packsges
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.7.0-1.el7.ans.noarch.rpm
        - docker
        - git
        - python2-pip

  - name: pip install docker-compose
    pip:
      name: docker-compose

  - name: Enable service docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: git clone awx
    git:
      repo: 'https://github.com/ansible/awx.git'
      dest: /awx
      clone: yes
      version: '2.0.1'

  - name: exe ansible-playbook
    command: ansible-playbook -i inventory install.yml
    args:
      chdir: /awx/installer

