---

- hosts: ESXi
  connection: local

  tasks:
    - name: Gather vmkernel facts
      vmware_vmkernel_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
      register: host_vmks

    - debug:
        var: host_vmks
