---
- hosts: ESXi
  connection: local

  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
      delegate_to: localhost
      register: vmfacts

    - debug:
        var: vmfacts.virtual_machines
