---

- hosts: ESXi
  connection: local

  tasks:
    - name: Get Canonical name
      vmware_target_canonical_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
        target_id: 1
      register: facts

    - debug:
        var: facts
