---

- hosts: ESXi
  connection: local

  tasks:
    - name: Gather facts about vmnics of an ESXi Host
      vmware_host_vmnic_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
      register: host_vmnics

    - debug:
        var: host_vmnics
