---
- hosts: ESXi
  connection: local

  tasks:
    - name: Gather disk facts
      vmware_guest_disk_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_userpass }}"
        datacenter: "{{ dc_name }}"
        name: "{{ vm_name }}"
        validate_certs: no
      delegate_to: localhost
      register: disk_facts

    - debug:
        var: disk_facts
