---
- hosts: ESXi
  connection: local

  tasks:
  - name: Gather virtual machines
    vmware_guest_facts:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_userpass }}"
      datacenter: "{{ dc_name }}"
      name: "{{ vm_name }}"
      validate_certs: no
    delegate_to: localhost
    register: disk_facts

  - debug:
      var: facts
