---
- hosts: ESXi
  connection: local

  tasks:
    - name: Get facts about ESXi Host
      vmware_host_config_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
      register: facts

    - debug:
        var: facts
