---

- hosts: ESXi
  connection: local

  tasks:
    - name: Gather facts ESXi Host
      vmware_host_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
      delegate_to: localhost
      register: host_facts

    - debug:
        var: host_facts
