---

- hosts: ESXi
  connection: local

  tasks:
    - name: Gather firewall facts about ESXi Host
      vmware_host_firewall_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
      delegate_to: localhost
      register: hosts_firewall_facts

    - debug:
        var: hosts_firewall_facts
