---
- hosts: ESXi
  connection: local

  tasks:
    - name: Gather facts from datastore facts
      vmware_datastore_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_userpass }}"
        datacenter: "{{ dc_name }}"
        validate_certs: no
      delegate_to: localhost
      register: facts

    - debug:
        var: facts
