---
- hosts: ESXi
  connection: local

  tasks:
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: powered-off
      delegate_to: localhost
      register: deploy

    - debug:
        var: deploy
