---

- hosts: ESXi
  connection: local

  tasks:
    - name: Gather facts about ESXi Host
      vmware_host_service_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_ip }}"
        validate_certs: no
      register: host_services

    - debug:
        var: host_services
