---
- hosts: bigip
  gather_facts: no
  connection: local

  tasks:
    - name: Create a pool 
      bigip_pool:
        server: "{{ bigip_server }}"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        server_port: 8443
        validate_certs: no
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost
